### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by doggybread** [infrost/DeeplxFile#1]
D:\Downloads\Programs>deeplxfile_v0.2.3_amd64.exe
Traceback (most recent call last):
  File "C:\Users\doggy\AppData\Local\Temp\ONEFIL~1\deeplxfile.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\doggy\AppData\Local\Temp\ONEFIL~1\Lib\compose.py", line 5, in <module Lib.compose>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\doggy\AppData\Local\Temp\ONEFIL~1\Lib\config.py", line 36, in <module Lib.config>
  File "C:\Users\doggy\AppData\Local\Temp\ONEFIL~1\Lib\config.py", line 26, in load_config
  File "C:\Users\doggy\AppData\Local\Temp\ONEFIL~1\json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 67: illegal multibyte sequence

**Comment by infrost** [comment]
问题出在部分中文版的Windows操作系统上，新版本理论上已修复该问题，可以尝试下载新版本运行试试。
